### ISSUE TITLE
При тестировании диска не проверяется существование директории

### ISSUE THREAD

**Issue by Pilat66** [tigrawap/goader#1]
Результат запуска, если директории tmp нет:

Maximum requests count

 Writes
Total requests: 300072
Total errors: 300072
Average OP/s:  9170
Average good OP/s:  1

**Comment by tigrawap** [comment]
By design. Дабы сподвигнуть на создание структуры заранее.
Создание/проверка существования директорий - дополнительный оверхед + автоматическое создание несуществующих директорий может привести к различным результатам между одинаковыми тестами.

Можно добавить флаг, который позволит создавать их автоматом, так что вся ответственность на том кто его выставит

**Comment by Pilat66** [comment]
Скорее надо не запускаться если нет директории

**Comment by tigrawap** [comment]
Если сделать так, то будет проблема с непостоянным поведением.
С одной стороны не запустится если нет верхней директории, с другой стороны запустится если нет поддиректорий, заранее проверить которые невозможно, например `-url=`tmp/NNNNN/RRRRR`

**Comment by tigrawap** [comment]
Есть флаг --mkdirs, который будет создавать директории которых нет в пути 
(включая различные паттерны, вроде XX/NN/RR/NN)
